name: new_learn_python
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  get: ^4.6.1
  flutter_highlight: ^0.7.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_native_splash: ^1.3.2
  flutter_lints: ^1.0.0
  url_launcher: ^6.0.18
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: '#000000'
  image: 'assets/images/LearnPython900.png'
  android: true
  ios: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/playstore.png"
  


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

